# Generated by Django 5.2.4 on 2025-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='confirmation_included_fields',
            field=models.TextField(blank=True, help_text='Comma-separated list of field names for confirmation emails'),
        ),
        migrations.AddField(
            model_name='notification',
            name='included_fields',
            field=models.TextField(blank=True, help_text="Comma-separated list of field names to include in emails (e.g. 'message,present_situation')"),
        ),
    ]
