# Generated by Django 5.2.4 on 2025-08-05 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0002_notification_confirmation_included_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='smtp_config',
            field=models.ForeignKey(blank=True, help_text='SMTP configuration for sending emails', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='formbuilder.smtpsenderconfig'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='smtp_config',
            field=models.ForeignKey(blank=True, help_text='SMTP configuration for sending this notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='formbuilder.smtpsenderconfig'),
        ),
    ]
