# Generated by Django 5.2.4 on 2025-08-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0003_alter_form_smtp_config_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smtpsenderconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='smtpsenderconfig',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smtpsenderconfig',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='smtpsenderconfig',
            unique_together={('email', 'smtp_host')},
        ),
    ]
