# Generated by Django 5.2.4 on 2025-08-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0004_alter_smtpsenderconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dynamic_receiver',
            field=models.BooleanField(default=False, help_text='Process placeholders in receiver email'),
        ),
    ]
