# Generated by Django 5.2.4 on 2025-08-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0005_notification_dynamic_receiver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smtpsenderconfig',
            unique_together={('email', 'smtp_host', 'smtp_username', 'smtp_password_encrypted')},
        ),
    ]
