# Generated by Django 5.2.4 on 2025-08-07 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0006_alter_smtpsenderconfig_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpsenderconfig',
            name='is_shared',
        ),
        migrations.AlterField(
            model_name='smtpsenderconfig',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smtp_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
