# Generated by Django 5.2.4 on 2025-08-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0007_remove_smtpsenderconfig_is_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
