# Generated by Django 5.2.4 on 2025-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0008_form_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='allowed_domains',
            field=models.JSONField(default=list, help_text="List of domains to submit to this form e.g., ['example.com', 'localhost']"),
        ),
    ]
